name: Minify and Deploy to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  minify-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the required Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install clean-css-cli -g
          npm install uglify-js -g

      # Minify CSS files
      - name: Minify CSS
        run: |
          find . -type f -name '*.css' -exec cleancss -o {} {} \;

      # Minify JS files
      - name: Minify JavaScript
        run: |
          find . -type f -name '*.js' -exec uglifyjs {} -o {} \;

      # Commit and push changes to gh-pages branch
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Minified JS and CSS and deployed to gh-pages"
          git push -f origin gh-pages
