name: Minify and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Minify CSS and JS files
        run: |
          npm install -g minify
          find . -type f \( -name "*.css" -o -name "*.js" \) -exec sh -c 'minify "$0" > "${0%.min}" && mv "${0%.min}" "$0"' {} \;

      - name: Configure git for pushing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stash changes
        run: git stash --include-untracked

      - name: Switch to gh-pages branch
        run: |
          git fetch origin
          if git rev-parse --verify origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout -b gh-pages
          fi

      - name: Apply stashed changes
        run: git stash pop || echo "No stashed changes to apply"

      - name: Add and commit changes
        run: |
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m 'Minify CSS and JS files and deploy to gh-pages'
          fi

      - name: Push changes to gh-pages branch
        run: git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
