name: Minify and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Minify CSS, JS, and HTML files
        run: |
          # Install the minify package globally
          npm install -g minify
          
          # Find and minify all CSS, JS, and HTML files in the repository
          find . -type f \( -name "*.css" -o -name "*.js" -o -name "*.html" \) -exec sh -c 'minify "$0" > "${0%.min}" && mv "${0%.min}" "$0"' {} \;

      - name: Configure git for pushing
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes to gh-pages branch
        run: |
          git fetch origin
          if git rev-parse --verify origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout -b gh-pages
          fi

          # Copy all changes from the main branch to the gh-pages branch
          git checkout main -- .
          
          # Add and commit changes
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m 'Minify CSS, JS, and HTML files and deploy to gh-pages'
            git push --force origin gh-pages
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
